name: Deploy to EKS

on:
  push:
    branches:
      - main 

env:
  ECR_REPOSITORY: weather-backend-repo
  REGION: eu-west-2
  CLUSTER_NAME: weather-cluster

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      # Step 3: Login to AWS ECR
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        id: build-and-push
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest"
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

      # Step 5: Configure kubectl for EKS
      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.REGION }} --name ${{ env.CLUSTER_NAME }}

      # Step 6: Update Kubernetes Deployment
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/weather-backend weather-backend=$IMAGE_URI
          kubectl rollout status deployment/weather-backend --timeout=60s

      # Step 7: Restart Pods
      - name: Restart Pods
        run: |
          kubectl rollout restart deployment/weather-backend
          kubectl rollout status deployment/weather-backend --timeout=60s

      # Step 8: Delete Untagged Images from ECR
      - name: Delete Untagged Images from ECR
        run: |
          # List all untagged images
          UNTAGGED_IMAGES=$(aws ecr list-images --repository-name ${{ env.ECR_REPOSITORY }} --query 'imageIds[?imageTag==`null`]' --output json)

          # Delete the untagged images if they exist
          if [ "$UNTAGGED_IMAGES" != "[]" ]; then
            echo "Deleting untagged images..."
            aws ecr batch-delete-image --repository-name ${{ env.ECR_REPOSITORY }} --image-ids "$UNTAGGED_IMAGES"
          else
            echo "No untagged images found."
          fi
