name: Deploy to EKS

on:
  push:
    branches:
      - main # Run the pipeline on pushes to the main branch

env:
  ECR_REPOSITORY: weather-backend-repo
  REGION: eu-west-2
  CLUSTER_NAME: weather-cluster

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      # Step 3: Login to AWS ECR
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest"
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"
      
          
      # Step 5: Configure kubectl for EKS
      - name: Configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.REGION }} --name ${{ env.CLUSTER_NAME }}

      # Step 6: Update Kubernetes Deployment
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/weather-backend weather-backend=${{ env.IMAGE_URI }}
          kubectl rollout status deployment/weather-backend --timeout=60s
      
